version: '3.9'

services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3030"]
      timeout: 10s
      retries: 5

  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 8080:8080
    working_dir: /app-backend
    command: dev 
    volumes: 
      - ./backend/src:/app-backend/src
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/db
      - DATABASE_USERNAME=uolProject
      - DATABASE_PASSWORD=1234
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:8080"]
      timeout: 10s
      retries: 5

  db:
    image: postgres
    hostname: postgres
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: uolProject
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db